name: GitHub Pages

on:
  push:
    branches: 
      - data

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Fetch data
    
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
