name: Update Metlink GTFS

on:
  schedule:
  - cron: '0 */6 * * *'
  push:
    branches:
      - data
      - scripts

jobs:
  gtfs-update:
    name: Update GTFS data
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch the scripts
        uses: actions/checkout@v1
        with:
          branch: scripts
        
      - name: Do all of it
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          git checkout scripts
          bash do-it.sh
